//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToneTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToneTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s gravenhage,The Hague,&apos;s Gravenhage,Den Haag,city (generic term),metropolis (generic term),urban center (generic term,
        ///&apos;tween decks,between decks,,,,,,
        ///0.22,twenty-two,firearm (generic term),piece (generic term),small-arm (generic term),,,
        ///.22-calibre,.22 caliber,.22-caliber,.22 calibre,diameter,diam (related term),,
        ///.22 caliber,.22-caliber,.22 calibre,.22-calibre,diameter,diam (related term),,
        ///.22 calibre,.22 caliber,.22-caliber,.22-calibre,diameter,diam (related term),,
        ///.38-caliber,.38 caliber,.38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewResource {
            get {
                return ResourceManager.GetString("NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word,Synonyms
        ///a-ok,a-okay
        ///a-okay,a-ok
        ///a-one,ace;A-one;crack;first-rate;super;tiptop;topnotch;top-notch;tops
        ///a.m.,ante meridiem
        ///a.m.,ante meridiem;A.M.
        ///a couple of,a few
        ///a few,a couple of
        ///a la mode,latest;in style;in vogue;modish
        ///abandoned,abandon|abandon;give up|vacate;empty;abandon|abandon;give up|abandon;forsake;desolate;desert
        ///abandoned,derelict;deserted
        ///abashed,embarrass;abash
        ///abashed,chagrined;embarrassed
        ///abasic,abatic
        ///abatic,abasic
        ///abaxial,dorsal
        ///abbreviated,abridge;foreshorten;abbrevi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
